### PR TITLE
Add ink! Analyzer

### PR DESCRIPTION
**Pull request by davidsemakula**
ink! Analyzer is a collection of modular and reusable libraries and tools for semantic analysis of ink! smart contract code.

References:
- [GitHub Organization](https://github.com/ink-analyzer/)
- [Introductory blog post](https://analyze.ink/blog/introducing-ink-analyzer)
- [W3F Grants Program application (completed)](https://github.com/davidsemakula/W3F-Grants-Program/blob/master/applications/ink-analyzer.md)

### CODE REVIEW

**Comment by davidsemakula** [comment]
Just confirming that I've signed the CLA 🙂

**Comment by davidsemakula** [comment]
@SkymanOne would be great to get this one merged too 🙂

**Comment by semuelle** [comment]
> would be great to get this one merged too 🙂

Agreed

**Comment by davidsemakula** [comment]
cc @cmichi

**Review by cmichi — APPROVED** [review]

**Comment by cmichi** [comment]
Thanks, David!

**Pull request merged**
